// SPDX-FileCopyrightText: 2026 Quentin Raimbaud
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by core/api/apigen from core/api/schema/core-api.schema.json. DO NOT EDIT.

/** Version of the contract, "major.minor". */
export const API_VERSION = "1.2";

/** No fields. */
export type Empty = Record<string, never>;

/** Why a request failed. */
export interface CoreError {
  code: ErrorCode;
  /**
   * For developers and logs; user interfaces show their own text for each
   * code.
   */
  message: string;
}

/**
 * invalid_request: not a valid request envelope. unknown_command: no such
 * command. invalid_params: the params do not match the command. not_found: an
 * ID refers to nothing. unsupported: this core cannot do it (for example a
 * login step type it does not know). timeout: the request took too long.
 * cancelled: login.cancel ended the request. closed: the core is closed.
 * network: the network failed or refused. internal: a bug or a local failure.
 */
export type ErrorCode =
  | "invalid_request"
  | "unknown_command"
  | "invalid_params"
  | "not_found"
  | "unsupported"
  | "timeout"
  | "cancelled"
  | "closed"
  | "network"
  | "internal";

export interface HelloResult {
  /** Version of this contract, "major.minor". */
  api_version: string;
  /** Version of the core build, for display and bug reports. */
  core_version: string;
}

/** A messaging network the core can connect to (Telegram, Signal...). */
export interface Network {
  network_id: string;
  /** Display name of the network. */
  name: string;
  /** Ways to add an account, in order of preference. */
  login_flows: LoginFlow[];
}

export interface LoginFlow {
  flow_id: string;
  name: string;
  description: string;
}

export interface NetworksListResult {
  networks: Network[];
}

/** An account of the user on one network. */
export interface Account {
  /** Opaque: user interfaces must not parse it. */
  account_id: string;
  network_id: string;
  /**
   * How the network names the account (phone number, username...). May be
   * empty.
   */
  name: string;
  state: AccountState;
  /** Explanation of the state for the user, when the network gave one. */
  error?: string;
}

/**
 * connecting: starting or catching up. connected: working.
 * transient_disconnect: temporarily unreachable, the core retries.
 * bad_credentials: the user must log in again. logged_out: the account was
 * logged out. unknown_error: failed for another reason.
 */
export type AccountState =
  | "connecting"
  | "connected"
  | "transient_disconnect"
  | "bad_credentials"
  | "logged_out"
  | "unknown_error";

export interface AccountsListResult {
  accounts: Account[];
}

export interface AccountEvent {
  account: Account;
}

export interface AccountsLogoutParams {
  account_id: string;
}

export interface LoginStartParams {
  network_id: string;
  flow_id: string;
}

export interface LoginSubmitParams {
  process_id: string;
  /** The value of every field of the step, by field ID. */
  values: Record<string, string>;
}

export interface LoginProcessParams {
  process_id: string;
}

/**
 * One step of a login process. user_input: show the fields and call
 * login.submit. display_and_wait: show the display and call login.wait.
 * complete: the account is added (account_id).
 */
export interface LoginStep {
  /** Identifies the login process in later login.* calls. Opaque. */
  process_id: string;
  type: LoginStepType;
  /**
   * Stable ID of this kind of step for the network (for example a 2FA password
   * step), for user interfaces that customize some steps.
   */
  step_id: string;
  /** Text to show to the user, from the network. May be empty. */
  instructions: string;
  /** For user_input steps. */
  fields?: LoginField[];
  display?: LoginDisplay;
  /** For complete steps: the account that was added. */
  account_id?: string;
}

export type LoginStepType = "user_input" | "display_and_wait" | "complete";

export interface LoginField {
  /** Key of the value in login.submit. */
  field_id: string;
  type: LoginFieldType;
  name: string;
  description: string;
  default_value?: string;
  /**
   * A regular expression the value should match, for checking it before
   * submitting.
   */
  pattern?: string;
  /** For select fields: the allowed values. */
  options?: string[];
}

/** A hint for the input control to show. */
export type LoginFieldType =
  | "username"
  | "password"
  | "phone_number"
  | "email"
  | "2fa_code"
  | "token"
  | "url"
  | "domain"
  | "select"
  | "captcha_code";

export interface LoginDisplay {
  type: LoginDisplayType;
  /**
   * The text to encode as a QR code, the emoji or the code to show. Absent for
   * nothing.
   */
  data?: string;
  /** Whether the user interface may offer to go back (login.cancel). */
  can_cancel: boolean;
}

export type LoginDisplayType = "qr" | "emoji" | "code" | "nothing";

export interface Conversation {
  /** Opaque: user interfaces must not parse it. */
  conversation_id: string;
  account_id: string;
  network_id: string;
  name: string;
  kind: ConversationKind;
  /** The person this conversation is linked to, if any. Since API 1.2. */
  person_id?: string;
}

export type ConversationKind = "direct" | "group";

export interface ConversationsListParams {
  /** Only the conversations of this account. */
  account_id?: string;
}

export interface ConversationsListResult {
  conversations: Conversation[];
}

export interface ConversationEvent {
  conversation: Conversation;
}

export interface Message {
  /** Opaque: user interfaces must not parse it. */
  message_id: string;
  conversation_id: string;
  /** Sent by the user, from this device or another one. */
  from_me: boolean;
  /** Display name of the sender. May be empty. */
  sender_name: string;
  /** When the message was sent, in milliseconds since the Unix epoch. */
  timestamp_ms: number;
  kind: MessageKind;
  /** The text of the message; for unsupported kinds, a fallback description. */
  text: string;
  status: MessageStatus;
  /** For failed messages: why, for the user, when the network said. */
  error?: string;
}

/**
 * text: a normal message. notice: an automated message. emote: an action ("/me
 * waves"). unsupported: a kind this version cannot show; text holds a
 * fallback.
 */
export type MessageKind = "text" | "notice" | "emote" | "unsupported";

/**
 * received: from someone else. sending, sent and failed: the delivery of a
 * message from the user.
 */
export type MessageStatus = "received" | "sending" | "sent" | "failed";

export interface MessagesListParams {
  conversation_id: string;
  /**
   * A cursor from a previous result: return the messages before it. Absent:
   * the latest messages.
   */
  before?: string;
  /** At most this many messages (default 50, at most 200). */
  limit?: number;
}

export interface MessagesListResult {
  /** Oldest first. */
  messages: Message[];
  /** Cursor for the older messages; absent when there are none. */
  before?: string;
}

export interface MessagesSendParams {
  conversation_id: string;
  text: string;
}

export interface MessagesSendResult {
  message: Message;
}

export interface MessageEvent {
  message: Message;
}

/**
 * A person of the user's, and the conversations with them that the user
 * merged. Since API 1.2.
 */
export interface Person {
  /** Opaque: user interfaces must not parse it. */
  person_id: string;
  name: string;
  /**
   * The person's conversations on this device, in the order they were linked.
   */
  conversation_ids: string[];
}

export interface PersonsListResult {
  persons: Person[];
}

export interface PersonsCreateParams {
  /**
   * Not blank, at most 256 bytes in UTF-8. The name of the first conversation
   * if absent.
   */
  name?: string;
  /** Direct conversations only. */
  conversation_ids: string[];
}

export interface PersonsRenameParams {
  person_id: string;
  /** Not blank, at most 256 bytes in UTF-8. */
  name: string;
}

export interface PersonsLinkParams {
  person_id: string;
  /** A direct conversation. */
  conversation_id: string;
}

export interface PersonsUnlinkParams {
  conversation_id: string;
}

export interface PersonsDeleteParams {
  person_id: string;
}

export interface PersonResult {
  person: Person;
}

export interface PersonEvent {
  person: Person;
}

export interface PersonDeletedEvent {
  person_id: string;
}

export interface PingPayload {
  payload: string;
}

export interface StatsResult {
  heap_alloc_bytes: number;
  heap_sys_bytes: number;
  goroutines: number;
}

/** Every command, by name, with the types of its params and result. */
export interface Commands {
  /**
   * Returns the versions of the API and of the core. A user interface calls it
   * first and refuses a core whose major API version differs from its own.
   */
  "core.hello": { params: Empty; result: HelloResult };
  /** Lists the networks this core can connect to. */
  "networks.list": { params: Empty; result: NetworksListResult };
  /** Lists the accounts the user added, on every network. */
  "accounts.list": { params: Empty; result: AccountsListResult };
  /**
   * Logs an account out of its network and removes it from this device, with
   * the conversations only it reached. The account first appears once more, in
   * an account.updated event with the state logged_out. Since API 1.1.
   */
  "accounts.logout": { params: AccountsLogoutParams; result: Empty };
  /**
   * Starts adding an account with one of the network's login flows, and
   * returns the first step.
   */
  "login.start": { params: LoginStartParams; result: LoginStep };
  /** Submits the fields of a user_input step, and returns the next step. */
  "login.submit": { params: LoginSubmitParams; result: LoginStep };
  /**
   * Waits until a display_and_wait step is done (for example a QR code scanned
   * on the phone), and returns the next step. Unlike other commands it has no
   * time limit: login.cancel ends it.
   */
  "login.wait": { params: LoginProcessParams; result: LoginStep };
  /**
   * Abandons a login process. Cancelling a finished or unknown process is not
   * an error.
   */
  "login.cancel": { params: LoginProcessParams; result: Empty };
  /** Lists the conversations of every account, or of one account. */
  "conversations.list": { params: ConversationsListParams; result: ConversationsListResult };
  /**
   * Returns the latest messages of a conversation, or the ones before a
   * cursor, oldest first.
   */
  "messages.list": { params: MessagesListParams; result: MessagesListResult };
  /**
   * Sends a text message. The message is stored at once with status sending;
   * its delivery is reported later by message.updated events.
   */
  "messages.send": { params: MessagesSendParams; result: MessagesSendResult };
  /**
   * Lists the persons the user merged conversations into, with their
   * conversations on this device. A person whose conversations are all absent
   * from this device (an account not added here) is not listed. Since API 1.2.
   */
  "persons.list": { params: Empty; result: PersonsListResult };
  /**
   * Creates a person from one or more direct conversations, taken from the
   * persons they belonged to. A person left without conversations is deleted
   * (person.deleted). Since API 1.2.
   */
  "persons.create": { params: PersonsCreateParams; result: PersonResult };
  /** Renames a person. Since API 1.2. */
  "persons.rename": { params: PersonsRenameParams; result: PersonResult };
  /**
   * Links a direct conversation to a person, taking it from the person it
   * belonged to. Since API 1.2.
   */
  "persons.link": { params: PersonsLinkParams; result: PersonResult };
  /**
   * Unlinks a conversation from its person, if it has one. A person left
   * without conversations is deleted. Since API 1.2.
   */
  "persons.unlink": { params: PersonsUnlinkParams; result: Empty };
  /** Deletes a person. Their conversations stay, unlinked. Since API 1.2. */
  "persons.delete": { params: PersonsDeleteParams; result: Empty };
  /** Returns its payload unchanged. Used to measure the cost of a call. */
  "debug.ping": { params: PingPayload; result: PingPayload };
  /**
   * Returns the memory of the Go runtime after a garbage collection, for leak
   * tests.
   */
  "debug.stats": { params: Empty; result: StatsResult };
}

/** Every event, by type, with the type of its data. */
export interface Events {
  /** An account was added or its connection state changed. */
  "account.updated": AccountEvent;
  /** A conversation was created or its name or kind changed. */
  "conversation.updated": ConversationEvent;
  /** A message was stored: received, or sent from this device. */
  "message.added": MessageEvent;
  /** A stored message changed, for example its delivery status. */
  "message.updated": MessageEvent;
  /**
   * A person was created, renamed, or their conversations changed. The
   * conversations whose person changed are sent again in conversation.updated
   * events. Since API 1.2.
   */
  "person.updated": PersonEvent;
  /**
   * A person was deleted, lost their last conversation, or has none left on
   * this device. Since API 1.2.
   */
  "person.deleted": PersonDeletedEvent;
  /**
   * The user interface read events too slowly and some were dropped: it must
   * read the state again (accounts, conversations, persons, messages).
   */
  "resync.required": Empty;
  /** The core was closed. It is the last event. */
  "core.closed": Empty;
}

export type CommandName = keyof Commands;
export type EventType = keyof Events;

export const COMMAND_NAMES: readonly CommandName[] = [
  "core.hello",
  "networks.list",
  "accounts.list",
  "accounts.logout",
  "login.start",
  "login.submit",
  "login.wait",
  "login.cancel",
  "conversations.list",
  "messages.list",
  "messages.send",
  "persons.list",
  "persons.create",
  "persons.rename",
  "persons.link",
  "persons.unlink",
  "persons.delete",
  "debug.ping",
  "debug.stats",
];

export const EVENT_TYPES: readonly EventType[] = [
  "account.updated",
  "conversation.updated",
  "message.added",
  "message.updated",
  "person.updated",
  "person.deleted",
  "resync.required",
  "core.closed",
];

/** Envelope of a request sent to the core. */
export interface Request<K extends CommandName = CommandName> {
  id: number;
  command: K;
  params?: Commands[K]["params"];
}

/** Envelope of the core's answer: exactly one of result and error. */
export type Response<K extends CommandName = CommandName> =
  | { id: number; result: Commands[K]["result"]; error?: never }
  | { id: number; error: CoreError; result?: never };

/** Envelope of an event sent by the core, discriminated by type. */
export type Event = { [K in EventType]: { type: K; data: Events[K] } }[EventType];
