// SPDX-FileCopyrightText: 2026 Quentin Raimbaud
// SPDX-License-Identifier: AGPL-3.0-or-later

package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"unicode"
)

// Header is the first lines of every generated file, after the comment
// marker of the language. The SPDX tags are split so that REUSE does not
// read them as the tags of this file.
const (
	spdxCopyright = "SPDX-" + "FileCopyrightText: 2026 Quentin Raimbaud"
	spdxLicense   = "SPDX-" + "License-Identifier: AGPL-3.0-or-later"
	generatedBy   = "Code generated by core/api/apigen from core/api/schema/core-api.schema.json. DO NOT EDIT."
)

// initialisms are written in capitals in Go names, as golint expects.
var initialisms = map[string]string{"id": "ID", "url": "URL", "api": "API", "ms": "MS", "qr": "QR", "2fa": "2FA"}

// goName turns a JSON name ("account_id", "core.hello", "2fa_code") into an
// exported Go name ("AccountID", "CoreHello", "2FACode").
func goName(s string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '.' || r == '-' }) {
		if up, ok := initialisms[part]; ok {
			b.WriteString(up)
			continue
		}
		r := []rune(part)
		r[0] = unicode.ToUpper(r[0])
		b.WriteString(string(r))
	}
	return b.String()
}

// GoPackage generates the Go types of the schema, in package pkg.
func GoPackage(s *Schema, pkg string) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// %s\n// %s\n\n// %s\n\npackage %s\n\n", spdxCopyright, spdxLicense, generatedBy, pkg)
	b.WriteString("import \"reflect\"\n\n")
	fmt.Fprintf(&b, "// APIVersion is the version of the contract, \"major.minor\".\nconst APIVersion = %q\n\n", s.Version)

	b.WriteString("// Command names.\nconst (\n")
	for _, c := range s.Commands {
		goComment(&b, "\t", c.Description)
		fmt.Fprintf(&b, "\tCommand%s = %q\n", goName(c.Name), c.Name)
	}
	b.WriteString(")\n\n// Event types.\nconst (\n")
	for _, e := range s.Events {
		goComment(&b, "\t", e.Description)
		fmt.Fprintf(&b, "\tEvent%s = %q\n", goName(e.Name), e.Name)
	}
	b.WriteString(")\n\n")

	b.WriteString("// Commands lists every command with the types of its params and result.\nvar Commands = []CommandSpec{\n")
	for _, c := range s.Commands {
		fmt.Fprintf(&b, "\t{Name: Command%s, Params: reflect.TypeFor[%s](), Result: reflect.TypeFor[%s]()},\n", goName(c.Name), c.Params, c.Result)
	}
	b.WriteString("}\n\n// Events lists every event with the type of its data.\nvar Events = []EventSpec{\n")
	for _, e := range s.Events {
		fmt.Fprintf(&b, "\t{Type: Event%s, Data: reflect.TypeFor[%s]()},\n", goName(e.Name), e.Data)
	}
	b.WriteString("}\n")

	for _, t := range s.Types {
		b.WriteString("\n")
		if t.Description == "" {
			goComment(&b, "", fmt.Sprintf("%s is $defs/%s of the schema.", t.Name, t.Name))
		} else {
			goComment(&b, "", t.Name+": "+t.Description)
		}
		if t.IsEnum() {
			fmt.Fprintf(&b, "type %s string\n\nconst (\n", t.Name)
			for _, v := range t.Enum {
				fmt.Fprintf(&b, "\t%s%s %s = %q\n", t.Name, goName(v), t.Name, v)
			}
			b.WriteString(")\n")
			continue
		}
		fmt.Fprintf(&b, "type %s struct {\n", t.Name)
		for _, f := range t.Fields {
			goComment(&b, "\t", f.Description)
			tag := f.JSONName
			typ := goType(f.Type)
			if !f.Required {
				tag += ",omitempty"
				if f.Type.Named != "" && !isEnum(s, f.Type.Named) {
					typ = "*" + typ
				}
			}
			fmt.Fprintf(&b, "\t%s %s `json:%q`\n", goName(f.JSONName), typ, tag)
		}
		b.WriteString("}\n")
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting the generated Go code: %w\n%s", err, b.Bytes())
	}
	return out, nil
}

func isEnum(s *Schema, name string) bool {
	for _, t := range s.Types {
		if t.Name == name {
			return t.IsEnum()
		}
	}
	return false
}

func goType(r *TypeRef) string {
	switch {
	case r.Named != "":
		return r.Named
	case r.Array != nil:
		return "[]" + goType(r.Array)
	case r.Map != nil:
		return "map[string]" + goType(r.Map)
	}
	return map[string]string{"string": "string", "integer": "int64", "number": "float64", "boolean": "bool"}[r.Primitive]
}

// goComment writes text as a Go comment, wrapped at about 80 columns.
func goComment(b *bytes.Buffer, indent, text string) {
	text = strings.TrimSuffix(strings.TrimSpace(text), ":")
	if text == "" {
		return
	}
	for _, line := range wrap(text, 76-len(indent)) {
		fmt.Fprintf(b, "%s// %s\n", indent, line)
	}
}

func wrap(text string, width int) []string {
	var lines []string
	line := ""
	for _, word := range strings.Fields(text) {
		if line != "" && len(line)+1+len(word) > width {
			lines = append(lines, line)
			line = ""
		}
		if line != "" {
			line += " "
		}
		line += word
	}
	return append(lines, line)
}
