// SPDX-FileCopyrightText: 2026 Quentin Raimbaud
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by core/api/apigen from core/api/schema/core-api.schema.json. DO NOT EDIT.

package api

import "reflect"

// APIVersion is the version of the contract, "major.minor".
const APIVersion = "1.0"

// Command names.
const (
	// Returns the versions of the API and of the core. A user interface calls it
	// first and refuses a core whose major API version differs from its own.
	CommandCoreHello = "core.hello"
	// Lists the networks this core can connect to.
	CommandNetworksList = "networks.list"
	// Lists the accounts the user added, on every network.
	CommandAccountsList = "accounts.list"
	// Starts adding an account with one of the network's login flows, and returns
	// the first step.
	CommandLoginStart = "login.start"
	// Submits the fields of a user_input step, and returns the next step.
	CommandLoginSubmit = "login.submit"
	// Waits until a display_and_wait step is done (for example a QR code scanned
	// on the phone), and returns the next step. Unlike other commands it has no
	// time limit: login.cancel ends it.
	CommandLoginWait = "login.wait"
	// Abandons a login process. Cancelling a finished or unknown process is not
	// an error.
	CommandLoginCancel = "login.cancel"
	// Lists the conversations of every account, or of one account.
	CommandConversationsList = "conversations.list"
	// Returns the latest messages of a conversation, or the ones before a cursor,
	// oldest first.
	CommandMessagesList = "messages.list"
	// Sends a text message. The message is stored at once with status sending;
	// its delivery is reported later by message.updated events.
	CommandMessagesSend = "messages.send"
	// Returns its payload unchanged. Used to measure the cost of a call.
	CommandDebugPing = "debug.ping"
	// Returns the memory of the Go runtime after a garbage collection, for leak
	// tests.
	CommandDebugStats = "debug.stats"
)

// Event types.
const (
	// An account was added or its connection state changed.
	EventAccountUpdated = "account.updated"
	// A conversation was created or its name or kind changed.
	EventConversationUpdated = "conversation.updated"
	// A message was stored: received, or sent from this device.
	EventMessageAdded = "message.added"
	// A stored message changed, for example its delivery status.
	EventMessageUpdated = "message.updated"
	// The user interface read events too slowly and some were dropped: it must
	// read the state again (accounts, conversations, messages).
	EventResyncRequired = "resync.required"
	// The core was closed. It is the last event.
	EventCoreClosed = "core.closed"
)

// Commands lists every command with the types of its params and result.
var Commands = []CommandSpec{
	{Name: CommandCoreHello, Params: reflect.TypeFor[Empty](), Result: reflect.TypeFor[HelloResult]()},
	{Name: CommandNetworksList, Params: reflect.TypeFor[Empty](), Result: reflect.TypeFor[NetworksListResult]()},
	{Name: CommandAccountsList, Params: reflect.TypeFor[Empty](), Result: reflect.TypeFor[AccountsListResult]()},
	{Name: CommandLoginStart, Params: reflect.TypeFor[LoginStartParams](), Result: reflect.TypeFor[LoginStep]()},
	{Name: CommandLoginSubmit, Params: reflect.TypeFor[LoginSubmitParams](), Result: reflect.TypeFor[LoginStep]()},
	{Name: CommandLoginWait, Params: reflect.TypeFor[LoginProcessParams](), Result: reflect.TypeFor[LoginStep]()},
	{Name: CommandLoginCancel, Params: reflect.TypeFor[LoginProcessParams](), Result: reflect.TypeFor[Empty]()},
	{Name: CommandConversationsList, Params: reflect.TypeFor[ConversationsListParams](), Result: reflect.TypeFor[ConversationsListResult]()},
	{Name: CommandMessagesList, Params: reflect.TypeFor[MessagesListParams](), Result: reflect.TypeFor[MessagesListResult]()},
	{Name: CommandMessagesSend, Params: reflect.TypeFor[MessagesSendParams](), Result: reflect.TypeFor[MessagesSendResult]()},
	{Name: CommandDebugPing, Params: reflect.TypeFor[PingPayload](), Result: reflect.TypeFor[PingPayload]()},
	{Name: CommandDebugStats, Params: reflect.TypeFor[Empty](), Result: reflect.TypeFor[StatsResult]()},
}

// Events lists every event with the type of its data.
var Events = []EventSpec{
	{Type: EventAccountUpdated, Data: reflect.TypeFor[AccountEvent]()},
	{Type: EventConversationUpdated, Data: reflect.TypeFor[ConversationEvent]()},
	{Type: EventMessageAdded, Data: reflect.TypeFor[MessageEvent]()},
	{Type: EventMessageUpdated, Data: reflect.TypeFor[MessageEvent]()},
	{Type: EventResyncRequired, Data: reflect.TypeFor[Empty]()},
	{Type: EventCoreClosed, Data: reflect.TypeFor[Empty]()},
}

// Empty: No fields.
type Empty struct {
}

// CoreError: Why a request failed.
type CoreError struct {
	Code ErrorCode `json:"code"`
	// For developers and logs; user interfaces show their own text for each code.
	Message string `json:"message"`
}

// ErrorCode: invalid_request: not a valid request envelope. unknown_command:
// no such command. invalid_params: the params do not match the command.
// not_found: an ID refers to nothing. unsupported: this core cannot do it (for
// example a login step type it does not know). timeout: the request took too
// long. cancelled: login.cancel ended the request. closed: the core is closed.
// network: the network failed or refused. internal: a bug or a local failure.
type ErrorCode string

const (
	ErrorCodeInvalidRequest ErrorCode = "invalid_request"
	ErrorCodeUnknownCommand ErrorCode = "unknown_command"
	ErrorCodeInvalidParams  ErrorCode = "invalid_params"
	ErrorCodeNotFound       ErrorCode = "not_found"
	ErrorCodeUnsupported    ErrorCode = "unsupported"
	ErrorCodeTimeout        ErrorCode = "timeout"
	ErrorCodeCancelled      ErrorCode = "cancelled"
	ErrorCodeClosed         ErrorCode = "closed"
	ErrorCodeNetwork        ErrorCode = "network"
	ErrorCodeInternal       ErrorCode = "internal"
)

// HelloResult is $defs/HelloResult of the schema.
type HelloResult struct {
	// Version of this contract, "major.minor".
	APIVersion string `json:"api_version"`
	// Version of the core build, for display and bug reports.
	CoreVersion string `json:"core_version"`
}

// Network: A messaging network the core can connect to (Telegram, Signal...).
type Network struct {
	NetworkID string `json:"network_id"`
	// Display name of the network.
	Name string `json:"name"`
	// Ways to add an account, in order of preference.
	LoginFlows []LoginFlow `json:"login_flows"`
}

// LoginFlow is $defs/LoginFlow of the schema.
type LoginFlow struct {
	FlowID      string `json:"flow_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// NetworksListResult is $defs/NetworksListResult of the schema.
type NetworksListResult struct {
	Networks []Network `json:"networks"`
}

// Account: An account of the user on one network.
type Account struct {
	// Opaque: user interfaces must not parse it.
	AccountID string `json:"account_id"`
	NetworkID string `json:"network_id"`
	// How the network names the account (phone number, username...). May be
	// empty.
	Name  string       `json:"name"`
	State AccountState `json:"state"`
	// Explanation of the state for the user, when the network gave one.
	Error string `json:"error,omitempty"`
}

// AccountState: connecting: starting or catching up. connected: working.
// transient_disconnect: temporarily unreachable, the core retries.
// bad_credentials: the user must log in again. logged_out: the account was
// logged out. unknown_error: failed for another reason.
type AccountState string

const (
	AccountStateConnecting          AccountState = "connecting"
	AccountStateConnected           AccountState = "connected"
	AccountStateTransientDisconnect AccountState = "transient_disconnect"
	AccountStateBadCredentials      AccountState = "bad_credentials"
	AccountStateLoggedOut           AccountState = "logged_out"
	AccountStateUnknownError        AccountState = "unknown_error"
)

// AccountsListResult is $defs/AccountsListResult of the schema.
type AccountsListResult struct {
	Accounts []Account `json:"accounts"`
}

// AccountEvent is $defs/AccountEvent of the schema.
type AccountEvent struct {
	Account Account `json:"account"`
}

// LoginStartParams is $defs/LoginStartParams of the schema.
type LoginStartParams struct {
	NetworkID string `json:"network_id"`
	FlowID    string `json:"flow_id"`
}

// LoginSubmitParams is $defs/LoginSubmitParams of the schema.
type LoginSubmitParams struct {
	ProcessID string `json:"process_id"`
	// The value of every field of the step, by field ID.
	Values map[string]string `json:"values"`
}

// LoginProcessParams is $defs/LoginProcessParams of the schema.
type LoginProcessParams struct {
	ProcessID string `json:"process_id"`
}

// LoginStep: One step of a login process. user_input: show the fields and call
// login.submit. display_and_wait: show the display and call login.wait.
// complete: the account is added (account_id).
type LoginStep struct {
	// Identifies the login process in later login.* calls. Opaque.
	ProcessID string        `json:"process_id"`
	Type      LoginStepType `json:"type"`
	// Stable ID of this kind of step for the network (for example a 2FA password
	// step), for user interfaces that customize some steps.
	StepID string `json:"step_id"`
	// Text to show to the user, from the network. May be empty.
	Instructions string `json:"instructions"`
	// For user_input steps.
	Fields  []LoginField  `json:"fields,omitempty"`
	Display *LoginDisplay `json:"display,omitempty"`
	// For complete steps: the account that was added.
	AccountID string `json:"account_id,omitempty"`
}

// LoginStepType is $defs/LoginStepType of the schema.
type LoginStepType string

const (
	LoginStepTypeUserInput      LoginStepType = "user_input"
	LoginStepTypeDisplayAndWait LoginStepType = "display_and_wait"
	LoginStepTypeComplete       LoginStepType = "complete"
)

// LoginField is $defs/LoginField of the schema.
type LoginField struct {
	// Key of the value in login.submit.
	FieldID      string         `json:"field_id"`
	Type         LoginFieldType `json:"type"`
	Name         string         `json:"name"`
	Description  string         `json:"description"`
	DefaultValue string         `json:"default_value,omitempty"`
	// A regular expression the value should match, for checking it before
	// submitting.
	Pattern string `json:"pattern,omitempty"`
	// For select fields: the allowed values.
	Options []string `json:"options,omitempty"`
}

// LoginFieldType: A hint for the input control to show.
type LoginFieldType string

const (
	LoginFieldTypeUsername    LoginFieldType = "username"
	LoginFieldTypePassword    LoginFieldType = "password"
	LoginFieldTypePhoneNumber LoginFieldType = "phone_number"
	LoginFieldTypeEmail       LoginFieldType = "email"
	LoginFieldType2FACode     LoginFieldType = "2fa_code"
	LoginFieldTypeToken       LoginFieldType = "token"
	LoginFieldTypeURL         LoginFieldType = "url"
	LoginFieldTypeDomain      LoginFieldType = "domain"
	LoginFieldTypeSelect      LoginFieldType = "select"
	LoginFieldTypeCaptchaCode LoginFieldType = "captcha_code"
)

// LoginDisplay is $defs/LoginDisplay of the schema.
type LoginDisplay struct {
	Type LoginDisplayType `json:"type"`
	// The text to encode as a QR code, the emoji or the code to show. Absent for
	// nothing.
	Data string `json:"data,omitempty"`
	// Whether the user interface may offer to go back (login.cancel).
	CanCancel bool `json:"can_cancel"`
}

// LoginDisplayType is $defs/LoginDisplayType of the schema.
type LoginDisplayType string

const (
	LoginDisplayTypeQR      LoginDisplayType = "qr"
	LoginDisplayTypeEmoji   LoginDisplayType = "emoji"
	LoginDisplayTypeCode    LoginDisplayType = "code"
	LoginDisplayTypeNothing LoginDisplayType = "nothing"
)

// Conversation is $defs/Conversation of the schema.
type Conversation struct {
	// Opaque: user interfaces must not parse it.
	ConversationID string           `json:"conversation_id"`
	AccountID      string           `json:"account_id"`
	NetworkID      string           `json:"network_id"`
	Name           string           `json:"name"`
	Kind           ConversationKind `json:"kind"`
}

// ConversationKind is $defs/ConversationKind of the schema.
type ConversationKind string

const (
	ConversationKindDirect ConversationKind = "direct"
	ConversationKindGroup  ConversationKind = "group"
)

// ConversationsListParams is $defs/ConversationsListParams of the schema.
type ConversationsListParams struct {
	// Only the conversations of this account.
	AccountID string `json:"account_id,omitempty"`
}

// ConversationsListResult is $defs/ConversationsListResult of the schema.
type ConversationsListResult struct {
	Conversations []Conversation `json:"conversations"`
}

// ConversationEvent is $defs/ConversationEvent of the schema.
type ConversationEvent struct {
	Conversation Conversation `json:"conversation"`
}

// Message is $defs/Message of the schema.
type Message struct {
	// Opaque: user interfaces must not parse it.
	MessageID      string `json:"message_id"`
	ConversationID string `json:"conversation_id"`
	// Sent by the user, from this device or another one.
	FromMe bool `json:"from_me"`
	// Display name of the sender. May be empty.
	SenderName string `json:"sender_name"`
	// When the message was sent, in milliseconds since the Unix epoch.
	TimestampMS int64       `json:"timestamp_ms"`
	Kind        MessageKind `json:"kind"`
	// The text of the message; for unsupported kinds, a fallback description.
	Text   string        `json:"text"`
	Status MessageStatus `json:"status"`
	// For failed messages: why, for the user, when the network said.
	Error string `json:"error,omitempty"`
}

// MessageKind: text: a normal message. notice: an automated message. emote: an
// action ("/me waves"). unsupported: a kind this version cannot show; text
// holds a fallback.
type MessageKind string

const (
	MessageKindText        MessageKind = "text"
	MessageKindNotice      MessageKind = "notice"
	MessageKindEmote       MessageKind = "emote"
	MessageKindUnsupported MessageKind = "unsupported"
)

// MessageStatus: received: from someone else. sending, sent and failed: the
// delivery of a message from the user.
type MessageStatus string

const (
	MessageStatusReceived MessageStatus = "received"
	MessageStatusSending  MessageStatus = "sending"
	MessageStatusSent     MessageStatus = "sent"
	MessageStatusFailed   MessageStatus = "failed"
)

// MessagesListParams is $defs/MessagesListParams of the schema.
type MessagesListParams struct {
	ConversationID string `json:"conversation_id"`
	// A cursor from a previous result: return the messages before it. Absent: the
	// latest messages.
	Before string `json:"before,omitempty"`
	// At most this many messages (default 50, at most 200).
	Limit int64 `json:"limit,omitempty"`
}

// MessagesListResult is $defs/MessagesListResult of the schema.
type MessagesListResult struct {
	// Oldest first.
	Messages []Message `json:"messages"`
	// Cursor for the older messages; absent when there are none.
	Before string `json:"before,omitempty"`
}

// MessagesSendParams is $defs/MessagesSendParams of the schema.
type MessagesSendParams struct {
	ConversationID string `json:"conversation_id"`
	Text           string `json:"text"`
}

// MessagesSendResult is $defs/MessagesSendResult of the schema.
type MessagesSendResult struct {
	Message Message `json:"message"`
}

// MessageEvent is $defs/MessageEvent of the schema.
type MessageEvent struct {
	Message Message `json:"message"`
}

// PingPayload is $defs/PingPayload of the schema.
type PingPayload struct {
	Payload string `json:"payload"`
}

// StatsResult is $defs/StatsResult of the schema.
type StatsResult struct {
	HeapAllocBytes int64 `json:"heap_alloc_bytes"`
	HeapSysBytes   int64 `json:"heap_sys_bytes"`
	Goroutines     int64 `json:"goroutines"`
}
